# **Pytorch Tutorial 2**
Video: https://youtu.be/VbqNn20FoHM

In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [2]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 0.6816, -0.6560,  1.2878,  0.5959, -0.4341],
        [-0.0794,  1.2763, -1.0594, -0.3716, -0.1289],
        [-1.0538, -0.0694, -0.1011, -0.1323,  1.1664],
        [-0.9838, -0.5490,  0.5071, -0.4493, -1.0720]])
tensor([[ 0.4114,  0.6226, -0.2837, -1.7898, -0.9561],
        [ 1.0701, -0.8265, -0.3009, -0.2499,  1.1979],
        [-1.0685, -0.6565,  1.5859, -0.7645,  0.5783],
        [ 1.9656,  0.8476,  0.9885, -0.5866, -0.5553]])
tensor([[-8.6437e-01,  2.1633e+00, -8.4745e-02, -3.3828e-01,  7.1322e-02],
        [ 5.8356e-01,  1.0707e-03, -2.5402e-01,  1.6148e-01, -1.0074e-02],
        [-1.0934e+00,  1.5942e+00, -2.7555e-01, -1.5468e-01, -1.8166e+00],
        [-1.7814e+00, -1.7924e+00,  6.5158e-02,  9.1207e-01, -8.8321e-01]])


In [3]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.2878)


In [4]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([0.6816, 1.2763, 1.2878, 0.5959, 1.1664])
tensor([0, 1, 0, 0, 2])


In [5]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.6816, 1.2763, 1.2878, 0.5959, 1.1664])
tensor([0, 1, 0, 0, 2])


In [6]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([0.6816, 1.2763, 1.2878, 0.5959, 1.1664])
tensor([0, 1, 0, 0, 2])


In [7]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[0.6816, 1.2763, 1.2878, 0.5959, 1.1664]])
tensor([[0, 1, 0, 0, 2]])


In [8]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.6816, 1.2763, 1.2878, 0.5959, 1.1664])
tensor([0, 1, 0, 0, 2])


/tmp/ipython-input-1447715753.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /pytorch/aten/src/ATen/native/Resize.cpp:30.)
  torch.max(x,0,False,out=p)


In [10]:
# 2-6
p = (m,idx)
torch.max(x,0,False,out=p)
# 必须加out
# torch.max(x,0,False,p)

print(p[0])
print(p[1])

tensor([0.6816, 1.2763, 1.2878, 0.5959, 1.1664])
tensor([0, 1, 0, 0, 2])


In [12]:
# 2-7
m, idx = torch.max(x,0,True)
# 方向不默认
# m, idx = torch.max(x,True)

In [13]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[ 0.6816,  0.6226,  1.2878,  0.5959, -0.4341],
        [ 1.0701,  1.2763, -0.3009, -0.2499,  1.1979],
        [-1.0538, -0.0694,  1.5859, -0.1323,  1.1664],
        [ 1.9656,  0.8476,  0.9885, -0.4493, -0.5553]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [14]:
import torch

In [16]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.randn(5).to("cpu")
y = model(x)

In [18]:
# 1. different device error (fixed)
x = torch.randn(5).to("cuda:0")
y = model(x)
print(y.shape)
print(x)
print(y)

torch.Size([1])
tensor([-0.4159,  0.9070, -1.8691, -0.9628,  1.2509], device='cuda:0')
tensor([-0.4145], device='cuda:0', grad_fn=<ViewBackward0>)


In [19]:
# 2. mismatched dimensions error 1
x = torch.randn(4,5)
y = torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [20]:
# 2. mismatched dimensions error 1 (fixed by transpose)
y = y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [21]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


OutOfMemoryError: CUDA out of memory. Tried to allocate 7.27 GiB. GPU 0 has a total capacity of 14.74 GiB of which 5.92 GiB is free. Process 2124 has 8.82 GiB memory in use. Of the allocated memory 8.68 GiB is allocated by PyTorch, and 11.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [22]:
# 3. cuda out of memory error (fixed, but it might take some time to execute)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [24]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

<built-in method type of Tensor object at 0x7d7f1c51b8f0>


RuntimeError: expected scalar type Long but found Float

In [27]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(1.7858)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [28]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [29]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [30]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(
                        dataset = dataset1,
                        shuffle = True,
                        batch_size = 1
              )
for datapoint in dataloader:
  print(datapoint)

['y']
['b']
['a']
['w']
['g']
['c']
['d']
['k']
['t']
['q']
['h']
['j']
['e']
['f']
['z']
['u']
['i']
['p']
['v']
['l']
['r']
['s']
['m']
['x']
['o']
['n']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [31]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['d']
['o']
['R']
['x']
['K']
['C']
['l']
['m']
['U']
['z']
['E']
['X']
['y']
['W']
['p']
['n']
['a']
['u']
['s']
['P']
['H']
['O']
['V']
['f']
['j']
['G']
['w']
['F']
['B']
['M']
['N']
['k']
['h']
['Z']
['S']
['J']
['t']
['L']
['b']
['v']
['T']
['Y']
['e']
['q']
['I']
['D']
['g']
['i']
['A']
['r']
['Q']
['c']
